### ISSUE TITLE
File Corrupted: AstroML/data/sdss_spectra/spec4000_corrected.npz

### ISSUE THREAD

**Issue by 8fdafs2** [diego0020/va_course_2015#2]
The file of **spec4000_corrected.npz** located at _AstroML/data/sdss_spectra/_ is corrupted.
Error message received when either trying to load it with numpy.load() or open it with 7-zip.
Is it possible to replace it with the right copy? :smiley: @cxnvcarol @diego0020 @juandoso

**Comment by juandoso** [comment]
The original source of the data file was moved/deleted and is no longer available. I suggest to check the updated version of the AstroML tutorial at https://github.com/astroML/astroML
